<body bgcolor="white">
<h1>PREMIER LEAGUE
</h1>
<div>
La Premier League, también conocida en el Reino Unido como The Premiership, es la máxima categoría del sistema de Ligas de fútbol de Inglaterra. Comenzó a disputarse en la temporada 1992-93 y desde entonces se ha celebrado sin interrupciones. En ella pueden también participar, por motivos históricos, aquellos clubes galeses que lo deseen, siempre que hayan competido ininterrumpidamente en el sistema de fútbol federado inglés desde, al menos, el 30 de junio de 1992. Este es el caso del Swansea City Association Football Club, club radicado en Gales participante de la liga y que ha llegado a representar a Inglaterra en competiciones europeas.
<br><br>Establecida la Primera División de Inglaterra denominada como The Football League en 1888 bajo amparo de The Football Association, se fusionó en 1892 con la Football Alliance para conformar el primer sistema de divisiones, y pasándose a denominar la principal categoría como Football League First Division. Dicho sistema fue ampliándose hasta que se produjo una escisión en la competición pasando a ser la Football League —que actualmente conforma tres divisiones— Premier League su principal exponente, mientras que la hasta el momento Primera División conjunta de Inglaterra y Gales de la Football League pasó a ser la Segunda.
<br><br>El actual formato fue establecido tras un acuerdo el 20 de febrero de 1992 entre los clubes de la First Division por el que decidían separarse de la Football League para tomar ventaja de un lucrativo contrato de derechos de televisión impulsado por ellos mismos. Es por tanto una competición de carácter privado o sociedad en la que los veinte clubes miembros actúan como accionistas a través de una persona delegada por cada representante, quienes rigen dicho comité junto con Dave Richards, director del mismo, y Richard Scudamore, su director ejecutivo.
<br><br>El torneo fue considerado por la Federación Internacional de Historia y Estadística de Fútbol de la FIFA como la liga más fuerte de la primera década del siglo xxi en Europa, superando a la Primera División de España y la Serie A de Italia que ocupaban el segundo y tercer lugar respectivamente.2
<br><br>Desde su segunda edición y hasta la temporada 2015-16 el nombre del patrocinador principal se reflejaba en su denominación oficial, siendo el último desde 2004 cuando se conocía como Barclays Premier League, circunstancia que dejó de ser así a partir de la temporada 2016-17, cuando desapareció cualquier alusión a los patrocinadores con el propósito de mantener una imagen comercial limpia. Desde entonces se conoce simplemente como Premier League.
<br><br>A lo largo de su historia seis clubes han resultado campeones, siendo el Manchester United Football Club el equipo más laureado con trece campeonatos. Chelsea Football Club, Arsenal Football Club, Manchester City Football Club, Blackburn Rovers Football Club y Leicester City Football Club completan el resto de títulos de las veinticinco temporadas del campeonato.
<br><br>El mayor número de puntos en una edición, con noventa y cinco, fue logrado en las temporada 2004-05 por el Chelsea F. C., logrando también el récord de goles en una edición con 103 en la temporada 2009-10.
</div>
</body>